[package]
name = "interactive-git"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dialoguer = "0.10.0"
console = "0.15.0"
git2 = "0.14.2"
thiserror = "1.0.30"
chrono = "0.4.2"
